// <auto-generated />
namespace Dalek_Mint.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201904052026074_editEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
